# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
for i in 1...10 do
		Post.create(:user_id => 1, :title => "Post " + i.to_s, :content => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lectus ligula, varius non fermentum non, luctus non nulla. Curabitur ac nisi vel mauris viverra lacinia. Nam diam erat, gravida tincidunt congue in, dapibus vel felis. Sed ligula dui, adipiscing vel pretium ac, egestas id diam. Sed nisi orci, volutpat et aliquam nec, malesuada quis est. Cras nec metus in tortor molestie placerat vel non lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ut massa in nisl faucibus iaculis. Vestibulum sed convallis lectus. Nulla pulvinar, nunc at interdum dapibus, velit sem imperdiet magna, vitae venenatis dolor ante eu metus.
		
		Cras at nunc eros, at pellentesque dui. Nunc id nibh et purus feugiat lacinia. Phasellus non est tellus. Nulla pellentesque elit non libero feugiat tristique. Mauris rutrum sapien quis enim dictum eget ultricies eros aliquet. Sed eleifend enim quis risus facilisis non vehicula sem mollis. Vestibulum placerat fringilla augue, a feugiat velit congue a. Ut lorem nibh, vestibulum non vestibulum a, vehicula aliquam felis. Donec vel sapien lectus, nec mattis eros. In mauris nibh, facilisis a dapibus facilisis, malesuada ac lorem. Nulla quis nulla mi, sed vehicula ligula. Quisque interdum varius nunc non pulvinar. Suspendisse sapien nisl, luctus ut posuere vitae, placerat sit amet eros. Etiam ac enim mi, eu vestibulum sem. Vivamus vel sapien mi, at volutpat nunc. Cras pulvinar pharetra molestie. Suspendisse potenti. Morbi ultrices lacinia lacus sed gravida. Sed ipsum diam, gravida quis interdum commodo, cursus sed nunc.
		
		Integer fringilla, urna in tempor tincidunt, lacus lectus auctor urna, at auctor leo est vestibulum mi. Curabitur condimentum viverra tellus ac lacinia. Duis non sapien elit. Aenean imperdiet tempus purus, sed bibendum justo sagittis sit amet. Mauris pretium sollicitudin dolor, vestibulum porta metus lobortis et. Ut egestas, ipsum sit amet tincidunt laoreet, lacus magna volutpat augue, vel blandit sapien dui in felis. Fusce vulputate sem quis dolor tincidunt consequat. Pellentesque dictum cursus mauris sed congue. Quisque hendrerit tempor bibendum. Aliquam feugiat purus quis tellus ornare congue sagittis purus porttitor. Sed in elementum metus. Vivamus vitae purus ac dolor dictum feugiat. Ut eget augue dolor.")
end